#!/usr/bin/env bash
# Re-record the manual CrazyGames evidence for the CURRENT build (evidence is tied to the dist/ fingerprint, so any new build
# makes it STALE). Run after `npm run build` and after the full browser harness is green, then `node tools/qa/report.mjs`.
# Every line states what was actually looked at; edit a line (or delete it) if the game changed so that it no longer holds.
# Items that stay open on purpose: CG-TECH-007 (real Edge), CG-TECH-008 (4 GB Chromebook), CG-TECH-013 (CrazyGames app safe
# areas), CG-TECH-016 (iOS audio), CG-GAME-006 / CG-QUAL-005 / CG-QUAL-007 (need the owner's play + ears), CG-QUAL-006 / CG-SUB-*
# (store text, covers, videos = launch package), CG-SDK-002 / CG-DATA-003 / CG-SUB-005 (Developer Portal).
set -e
cd "$(dirname "$0")/../.."
R="node tools/qa/record.mjs"

$R CG-TECH-010 PASS --evidence "Looked at the intro screen at 800x450, 907x510, 1280x720 (landscape) and 390x844: nothing clipped or overlapping, text readable; result and near-miss dialogs fit at 1280x720; the harness found no scroll, overflow or overlap at 12 sizes (smallest text 12 px)" --method "browser-qa viewports (12 sizes) + looked at qa/shots/viewport-*.png and ad-ui-*.png"
$R CG-GAME-002 PASS --evidence "Looked at the CrazyGames iframe sizes 800x450, 907x510 and 1280x720 at DPR 1 and 390x844 portrait: title, hint, upgrade cards and both buttons are readable and not clipped; the other named sizes show no overflow in the harness" --method "browser-qa viewports + looked at qa/shots/viewport-*.png"
$R CG-TECH-017 PASS --evidence "platform.js reads SDK user.systemInfo (locale, device.type, applicationType); main.js uses device.type for the touch hint and locale for the language; isCrazyGamesApp wired" --method "code read: src/platform/platform.js:222, src/main.js:122,132"
$R CG-GAME-001 PASS --evidence "No PLAY button: the city intro shows a pulsing hold hint and the first hold starts the run (0 extra clicks); touch scenario: one tap on an 800x450 touch device -> phase=run" --method "browser-qa touch + input-strike scenarios; qa/shots/viewport-800x450.png"
$R CG-GAME-005 PASS --evidence "English is the complete string table; initI18n(systemInfo.locale) picks a shipped language and falls back to English; no other language is shipped, so no inaccurate translation exists" --method "code read: src/core/i18n.js, src/main.js:122"
$R CG-GAME-007 PASS --evidence "Own game: no shipped model/texture files (0 assets in manifest), geometry from code, ZzFX procedural sounds (MIT), Lilita One font (OFL); web search 2026-10-01 found no game named Storm Grid on Steam/itch/CrazyGames/Poki" --method "check-licenses.mjs + check-poly.mjs PASS; docs/ORIGINALITY.md; web search"
$R CG-GAME-010 PASS --evidence "Content is a toy city lit by cartoon lightning: no people, blood, weapons, gambling, real money or horror; no chat; suits PEGI 3-7 content, audience 13+, not targeted at kids" --method "content review of all screens (qa/shots) and the string table"
$R CG-QUAL-003 PASS --evidence "Onboarding happens inside the first run: pulsing hold hint on the intro, an onboarding pill while charging until the first SUPERCHARGE release; nothing blocks play so it is skippable; icon plus two short lines" --method "code read src/main.js (hint, pill); screenshot qa/shots/viewport-800x450.png"
$R CG-QUAL-004 PASS --evidence "Rewarded buttons carry a video icon and the reward text (+2 strikes, Claim x3); the coin alternative has the same size/font/gradient and the decline is equal; no delayed or hidden close" --method "browser-qa ad-ui-style (equal size/font/colours) + looked at qa/shots/ad-ui-win.png and viewport-800x450.png"
$R CG-SDK-008 PASS --evidence "setGameContext({city}) is called when a city starts and cleared on leaving; the sdk-events scenario saw setGameContext > gameplayStop > clearGameContext in order" --method "browser-qa sdk-events; src/main.js (tryStartRun)"
$R CG-SDK-009 PASS --evidence "happytime fires only for the first FULL POWER ever and for reaching city 20 and city 40, never per city or per item" --method "code read: src/main.js (happytime call); browser-qa sdk-events saw it once"
$R CG-ADS-002 PASS --evidence "Midgame is requested only with a break context (level-complete-next / retry) from city 4 on, never during active gameplay and not on menu/shop buttons; ads.js refuses without a context" --method "code read src/core/ads.js, src/main.js; browser-qa ads-fill + ad-ui PASS"
$R CG-ADS-006 PASS --evidence "No custom midgame cooldown in the code: ads.midgame asks at every break from city 4 and the SDK paces it; only the first-midgame level (retention) is configured" --method "code read src/core/ads.js, src/config.js"
$R CG-ADS-007 PASS --evidence "Every rewarded button shows a video icon and the reward; none has a hidden or delayed close; all offers can simply be ignored" --method "browser-qa ad-ui-style; looked at qa/shots/ad-ui-win.png, ad-ui-ready.png, ad-ui-fail-revive.png"
$R CG-ADS-008 PASS --evidence "Claim and Claim x3 are the same .btn (size, font, gradient); +2 strikes (video) sits next to +2 strikes 60 coins in equal size; the harness found equal size/font/colours for every offer" --method "browser-qa ad-ui-style + screenshots ad-ui-win.png / viewport-800x450.png"
$R CG-ADS-009 PASS --evidence "No rewarded offer is visible during active gameplay (checked at +0.3 s and +1.5 s of a run); offers live on the intro, result, near-miss and shop screens only" --method "browser-qa ad-ui scenario"
$R CG-ADS-010 PASS --evidence "Every reward needs at most one rewarded ad; offers are independent and capped per session/cooldown; the midgame is skipped for the break if a rewarded ad was shown" --method "code read: src/core/ads.js, src/main.js (rewardedShown)"
$R CG-ADS-011 PASS --evidence "Caps: revive once per session and only at 85-99% powered, boost after 2 runs and 120 s cooldown, free upgrade 180 s, shop cash 180 s with a visible timer, daily gift once a day; midgame from city 4" --method "code read src/config.js; browser-qa revive-offer + shop"
$R CG-ADS-012 PASS --evidence "All 7 rewarded surfaces have a coin or play alternative (Claim, +2 strikes for coins, upgrades for coins, bolts unlocked with coins); ad blocker and ads-off runs stay fully playable" --method "browser-qa ads-basic-launch, adblock, shop, ad-ui-style"
$R CG-ADS-014 PASS --evidence "The one-more-strike revive is limited to once per session and only at 85-99% powered; none at 5% powered; the offer expires without an ad request; no offer after a watched revive" --method "browser-qa revive-offer scenario"
$R CG-ADS-015 PASS --evidence "A break gets a midgame OR a rewarded continue: ads.js refuses the second one, and main.js skips the midgame when a rewarded ad was shown on that result" --method "code read src/core/ads.js, src/main.js"
$R CG-DATA-002 PASS --evidence "Save goes through the SDK data module with a localStorage fallback; reload keeps city 2 and 470 coins; the save is 369 bytes (limit 1 MB); writes are debounced 1 s and flushed on level end and tab hide" --method "browser-qa persistence + tab-hidden; src/core/save.js"
